export const MENUITEMS = [
  {
    path: "/Locations",
    title: "Locations",
    icon: "shield",
    type: "link",
    roles: ["SystemAdmin"],
  },
  {
    path: "/blogs",
    title: "Blogs",
    icon: "shield",
    type: "link",
    roles: ["Independent", "Organization", "SystemAdmin"],
  },
  {
    path: "/organizations",
    title: "Organizations",
    icon: "shield",
    type: "link",
    roles: ["Independent", "Organization", "SystemAdmin"],
  },
  {
    path: "/userprofiles",
    title: "Users",
    icon: "shield",
    type: "link",
    roles: ["SystemAdmin", "Organization"],
  },
  {
    path: "/messages",
    title: "Messages",
    icon: "shield",
    type: "link",
    roles: ["Independent", "Organization", "SystemAdmin"],
  },
  {
    path: "/plans",
    title: "Plans",
    icon: "shield",
    type: "link",
    roles: ["Independent", "Organization", "SystemAdmin"],
  },
  {
    path: "/feed",
    title: "Feed",
    icon: "shield",
    type: "link",
    roles: ["Independent", "Organization", "SystemAdmin"],
  },
  {
    path: "/groups",
    title: "Groups",
    icon: "shield",
    type: "link",
    roles: ["Independent", "Organization", "SystemAdmin"],
  },
];
